# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/warpersan/.unrealengine/Linux_Unreal_Engine_5.8.2

TARGETS = \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	tp_8iar125_tp1-Android-DebugGame  \
	tp_8iar125_tp1-Android-Development  \
	tp_8iar125_tp1-Android-Shipping  \
	tp_8iar125_tp1-Linux-DebugGame  \
	tp_8iar125_tp1-Linux-Development  \
	tp_8iar125_tp1-Linux-Shipping  \
	tp_8iar125_tp1-LinuxArm64-DebugGame  \
	tp_8iar125_tp1-LinuxArm64-Development  \
	tp_8iar125_tp1-LinuxArm64-Shipping  \
	tp_8iar125_tp1 \
	tp_8iar125_tp1Editor-Linux-DebugGame  \
	tp_8iar125_tp1Editor-Linux-Development  \
	tp_8iar125_tp1Editor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend tp_8iar125_tp1Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug tp_8iar125_tp1Editor-Linux-Debug


ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

tp_8iar125_tp1-Android-DebugGame:
	 $(BUILD) tp_8iar125_tp1 Android DebugGame  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-Android-Development:
	 $(BUILD) tp_8iar125_tp1 Android Development  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-Android-Shipping:
	 $(BUILD) tp_8iar125_tp1 Android Shipping  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-Linux-DebugGame:
	 $(BUILD) tp_8iar125_tp1 Linux DebugGame  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-Linux-Development:
	 $(BUILD) tp_8iar125_tp1 Linux Development  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-Linux-Shipping:
	 $(BUILD) tp_8iar125_tp1 Linux Shipping  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-LinuxArm64-DebugGame:
	 $(BUILD) tp_8iar125_tp1 LinuxArm64 DebugGame  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-LinuxArm64-Development:
	 $(BUILD) tp_8iar125_tp1 LinuxArm64 Development  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1-LinuxArm64-Shipping:
	 $(BUILD) tp_8iar125_tp1 LinuxArm64 Shipping  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1: tp_8iar125_tp1-Linux-Development

tp_8iar125_tp1Editor-Linux-DebugGame:
	 $(BUILD) tp_8iar125_tp1Editor Linux DebugGame  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1Editor-Linux-Development:
	 $(BUILD) tp_8iar125_tp1Editor Linux Development  -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" $(ARGS)

tp_8iar125_tp1Editor: tp_8iar125_tp1Editor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/warpersan/Projects/Unreal Engine/tp_8iar125_tp1/tp_8iar125_tp1.uproject" -Game 

.PHONY: $(TARGETS)
